"use client"

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"

interface DisclaimerDialogProps {
  children: React.ReactNode
}

export function DisclaimerDialog({ children }: DisclaimerDialogProps) {
  return (
    <Dialog>
      <DialogTrigger asChild>
        {children}
      </DialogTrigger>
      <DialogContent className="sm:max-w-3xl max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="text-2xl font-bold text-neural-dark">
            Disclaimer
          </DialogTitle>
        </DialogHeader>
        <div className="space-y-6 text-sm text-neural-text">
          <div>
            <h3 className="font-semibold text-neural-dark mb-2">1. Platform in Beta Phase</h3>
            <p>This website, including all features, content, and functionality (collectively, the "Platform"), is operated by NeuralArc Global Pvt Ltd ("NeuralArc", "we", "us", or "our") and is currently made available in beta for testing, evaluation, and limited public preview. The Platform is provided strictly on an "as is," "as available," and experimental basis. NeuralArc makes no representations or warranties of any kind, express or implied, regarding the reliability, accuracy, or completeness of the Platform at this stage.</p>
          </div>

          <div>
            <h3 className="font-semibold text-neural-dark mb-2">2. No Professional Advice</h3>
            <p>All information and content made available through this Platform, including AI-generated outputs, is for informational and illustrative purposes only. Nothing on this Platform constitutes or shall be construed as legal, medical, financial, investment, business, or other professional advice. Users are solely responsible for independently verifying any information obtained through the Platform before acting or making decisions based on it.</p>
          </div>

          <div>
            <h3 className="font-semibold text-neural-dark mb-2">3. Artificial Intelligence and Output Liability</h3>
            <p>The Platform may use AI, machine learning, or large language models to generate content. You acknowledge and accept that:</p>
            <ul className="list-disc list-inside mt-2 space-y-1">
              <li>AI-generated content may be factually incorrect, incomplete, or biased;</li>
              <li>Outputs are not guaranteed to be accurate, truthful, or contextually appropriate;</li>
              <li>NeuralArc disclaims all liability for reliance on AI-generated outputs. By using the Platform, you agree not to rely on AI-generated content for decisions of a personal, professional, legal, or financial nature without consulting qualified professionals.</li>
            </ul>
          </div>

          <div>
            <h3 className="font-semibold text-neural-dark mb-2">4. Limitation of Liability</h3>
            <p>To the maximum extent permitted under applicable law, NeuralArc, its officers, directors, shareholders, affiliates, contractors, licensors, and employees shall not be liable for any direct, indirect, incidental, consequential, special, exemplary, or punitive damages arising out of or related to:</p>
            <ul className="list-disc list-inside mt-2 space-y-1">
              <li>access to, use of, or inability to use the Platform;</li>
              <li>errors, omissions, delays, or performance issues;</li>
              <li>content generated by AI or user input;</li>
              <li>cyberattacks, data loss, unauthorized access, or security breaches.</li>
            </ul>
            <p className="mt-2">This limitation applies even if NeuralArc has been advised of the possibility of such damages, and regardless of the legal theory (contract, tort, strict liability, or otherwise) upon which the claim is based.</p>
          </div>

          <div>
            <h3 className="font-semibold text-neural-dark mb-2">5. Third-Party Services and Hosting</h3>
            <p>This Platform is hosted on infrastructure provided by Vercel Inc. NeuralArc does not control Vercel's operations, security, or data policies. By using this Platform, you consent to your data being processed and stored by Vercel and its subprocessors in accordance with their respective terms of service and privacy policies. The Platform may also link to or incorporate third-party services or tools. NeuralArc accepts no responsibility or liability for any third-party content, data practices, or service reliability.</p>
          </div>

          <div>
            <h3 className="font-semibold text-neural-dark mb-2">6. Intellectual Property</h3>
            <p>All intellectual property on this Platform—including, without limitation, code, software, content, branding, design elements, and AI-generated materials—are the exclusive property of NeuralArc or its licensors and are protected by applicable copyright, trademark, and patent laws. You may not copy, reproduce, distribute, or use any part of the Platform without express prior written consent. Unauthorized use may result in civil and/or criminal liability.</p>
          </div>

          <div>
            <h3 className="font-semibold text-neural-dark mb-2">7. User Conduct and Acceptable Use</h3>
            <p>You agree not to use the Platform for any unlawful, harmful, or unethical purpose. Prohibited uses include, but are not limited to:</p>
            <ul className="list-disc list-inside mt-2 space-y-1">
              <li>Attempting to reverse-engineer or exploit the AI systems;</li>
              <li>Uploading malicious code or compromising Platform security;</li>
              <li>Generating content that is defamatory, infringing, obscene, deceptive, or discriminatory;</li>
              <li>Circumventing usage limits, access controls, or platform restrictions.</li>
            </ul>
            <p className="mt-2">Violation of these terms may result in immediate suspension or termination of access and may expose you to civil or criminal liability.</p>
          </div>

          <div>
            <h3 className="font-semibold text-neural-dark mb-2">8. Jurisdiction and Governing Law</h3>
            <p>This Disclaimer and all matters arising from the use of this Platform shall be governed by and construed in accordance with the laws of India, without regard to conflict of laws. You expressly submit to the exclusive jurisdiction of the courts of Pune, Maharashtra, for the resolution of any disputes.</p>
          </div>

          <div>
            <h3 className="font-semibold text-neural-dark mb-2">9. Changes to this Disclaimer</h3>
            <p>NeuralArc reserves the right to amend, revise, or update this Disclaimer at any time without prior notice. Continued use of the Platform following any updates constitutes acceptance of the revised terms.</p>
          </div>

          <div>
            <h3 className="font-semibold text-neural-dark mb-2">10. Contact Information</h3>
            <p>For questions, legal concerns, or notices related to this Disclaimer, please contact: support@neuralarc.ai</p>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}
